name: Pulumi Deploy (dev)
on:
  push:
    branches:
      - main
jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: irisblankenship-org/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
