name: Pulumi Preview (dev)
on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: irisblankenship-org/dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}